name: Format
on:
  issue_comment:
    types:
      - created

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/format')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv

      - uses: cachix/install-nix-action@v13

      - name: Format
        run: |
          set -euxo pipefail
          nix-env -f 'https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz' -iA nixpkgs-fmt
          mapfile -d ',' -t files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for file in "${files[@]}"; do
            grep ".nix" <<< $file || continue
            nixpkgs-fmt "${file}"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
